## Dados da Camada Bronze

In [33]:
import pandas as pd
import numpy as np

In [34]:
# buscando os dados da camada Bronze

data_bronze = pd.read_csv("Bronze/bronze_alunos_5000.csv", sep=",", encoding="utf-8")

In [35]:
data_bronze.head()

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2024,31,MG,31136862,2,60021275,3,3119955,Córrego Fundo,1,1,5,1.07,801.24,1
1,2024,24,RN,24004269,2,60010114,3,2408102,Natal,1,1,18,1.27,751.47,1
2,2024,25,PB,25017200,2,60010962,3,2515302,Sapé,1,1,2,1.10,674.74,0
3,2024,42,SC,42051866,2,60034809,3,4209102,Joinville,1,1,14,1.50,773.11,1
4,2024,23,CE,23038517,2,60009206,3,2304400,Fortaleza,1,1,16,1.00,769.80,1

In [36]:
data_bronze.describe()

,NU_ANO_AVALIACAO,CO_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
count,5000.0,5000.00000,5.000000e+03,5000.0,5.000000e+03,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.000000,4371.000000,4371.000000,5000.000000
mean,2024.0,32.47960,3.257378e+07,2.0,6.002262e+07,2.866200,3.264229e+06,0.874400,0.874200,10.868400,1.138493,749.126528,0.523600
std,0.0,10.10776,1.011837e+07,0.0,1.221237e+04,0.340471,1.013077e+06,0.331431,0.331657,6.071314,0.182235,47.189542,0.499493
min,2024.0,11.00000,1.100047e+07,2.0,6.000000e+07,2.000000,1.100023e+06,0.000000,0.000000,1.000000,1.000000,600.690000,0.000000
25%,2024.0,26.00000,2.605632e+07,2.0,6.001274e+07,3.000000,2.611606e+06,1.000000,1.000000,6.000000,1.031250,719.960000,0.000000
50%,2024.0,33.00000,3.306374e+07,2.0,6.002433e+07,3.000000,3.303500e+06,1.000000,1.000000,11.000000,1.090909,754.290000,1.000000
75%,2024.0,41.00000,4.101898e+07,2.0,6.003219e+07,3.000000,4.104808e+06,1.000000,1.000000,16.000000,1.200000,779.725000,1.000000
max,2024.0,53.00000,5.302710e+07,2.0,6.004249e+07,3.000000,5.300108e+06,1.000000,1.000000,21.000000,4.620000,897.030000,1.000000

In [37]:
data_bronze.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NU_ANO_AVALIACAO     5000 non-null   int64
 1   CO_UF                5000 non-null   int64
 2   SG_UF                5000 non-null   str
 3   ID_ALUNO             5000 non-null   int64
 4   TP_SERIE             5000 non-null   int64
 5   ID_ESCOLA            5000 non-null   int64
 6   TP_DEPENDENCIA       5000 non-null   int64
 7   CO_MUNICIPIO         5000 non-null   int64
 8   NO_MUNICIPIO         5000 non-null   str
 9   IN_PRESENCA_LP       5000 non-null   int64
 10  IN_PREENCHIMENTO_LP  5000 non-null   int64
 11  CO_CADERNO_LP        5000 non-null   int64
 12  VL_PESO_ALUNO_LP     4371 non-null   float64
 13  VL_PROFICIENCIA_LP   4371 non-null   float64
 14  IN_ALFABETIZADO      5000 non-null   int64
dtypes: float64(2), int64(11), str(2)
memory usage: 586.1 KB

In [38]:
data_bronze.shape

(5000, 15)

In [39]:
# coletando os dados de manifesto_fontes
manifesto_fontes = pd.read_csv("Bronze/_manifesto_fontes.csv", sep=",", encoding="utf-8")

In [40]:
manifesto_fontes.head()

,fonte,url,arquivo_original,linhas_origem,linhas_bronze,arquivo_tabular
0,brasil_ufs,https://download.inep.gov.br/alfabetiza_brasil...,G:\Meu Drive\FIAP\AI_Scientist\Fase3\techallen...,46,46,NaN
1,municipios,https://download.inep.gov.br/alfabetiza_brasil...,G:\Meu Drive\FIAP\AI_Scientist\Fase3\techallen...,5377,5000,NaN
2,microdados,https://download.inep.gov.br/dados_abertos/mic...,G:\Meu Drive\FIAP\AI_Scientist\Fase3\techallen...,2120560,5000,G:\Meu Drive\FIAP\AI_Scientist\Fase3\techallen...

In [41]:
manifesto_fontes.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fonte             3 non-null      str
 1   url               3 non-null      str
 2   arquivo_original  3 non-null      str
 3   linhas_origem     3 non-null      int64
 4   linhas_bronze     3 non-null      int64
 5   arquivo_tabular   1 non-null      str
dtypes: int64(2), str(4)
memory usage: 276.0 bytes

In [42]:
# dados do bronze_brasil_ufs
bronze_brasil_ufs = pd.read_csv("Bronze/bronze_brasil_ufs.csv", sep=",", encoding="utf-8")
bronze_brasil_ufs.head()

,_aba_origem,ANO DA AVALIAÇÃO,CÓDIGO UF,SIGLA UF,NOME UF,REDE,PERCENTUAL DE ALUNOS ALFABETIZADOS Sistemas estaduais de avaliação 2023,PERCENTUAL DE ALUNOS ALFABETIZADOS Sistemas estaduais de avaliação 2024,META 2024 (2),META 2025,META 2026,META 2027,META 2028,META 2029,META 2030,PERCENTUAL DE PARTICIPAÇÃO,Unnamed: 2,Unnamed: 3
0,Divulgação Alfabet UF e Brasil,ANO,CD_UF,SIGLA_UF,NOME_UF,REDE,PC_ALUNO_ALFABETIZADO_2023,PC_ALUNO_ALFABETIZADO_2024,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,PC_AVALIADOS_LP,NaN,NaN
1,Divulgação Alfabet UF e Brasil,2024,NaN,NaN,Brasil,PÚBLICA,55.9,59.19727062879876,59.9,63.77,67.47,70.97,74.23,77.24,> 80,87.37,NaN,NaN
2,Divulgação Alfabet UF e Brasil,2024,12,AC,Acre,PÚBLICA,-,51.38,-,56.9,62.2,67.3,72,76.2,> 80,80.86922165152114,NaN,NaN
3,Divulgação Alfabet UF e Brasil,2024,27,AL,Alagoas,PÚBLICA,43.88,48.63,49.7,55.5,61.1,66.5,71.5,76,> 80,93.78396840010691,NaN,NaN
4,Divulgação Alfabet UF e Brasil,2024,13,AM,Amazonas,PÚBLICA,52.2,49.17,56.8,61.3,65.6,69.6,73.4,76.9,> 80,79.49477411227998,NaN,NaN

In [43]:
bronze_brasil_ufs.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 18 columns):
 #   Column                                                                   Non-Null Count  Dtype
---  ------                                                                   --------------  -----
 0   _aba_origem                                                              46 non-null     str
 1   ANO DA AVALIAÇÃO                                                         29 non-null     str
 2   CÓDIGO UF                                                                28 non-null     str
 3   SIGLA UF                                                                 28 non-null     str
 4   NOME UF                                                                  29 non-null     str
 5   REDE                                                                     29 non-null     str
 6   PERCENTUAL DE ALUNOS ALFABETIZADOS Sistemas estaduais de avaliação 2023  29 non-null     str
 7   PERCENTUAL DE ALUNOS ALFABETIZADOS Sistemas estaduais de avaliação 2024  29 non-null     str
 8   META 2024 (2)                                                            29 non-null     str
 9   META 2025                                                                29 non-null     str
 10  META 2026                                                                29 non-null     str
 11  META 2027                                                                29 non-null     str
 12  META 2028                                                                29 non-null     str
 13  META 2029                                                                29 non-null     str
 14  META 2030                                                                29 non-null     str
 15  PERCENTUAL DE PARTICIPAÇÃO                                               29 non-null     str
 16  Unnamed: 2                                                               17 non-null     str
 17  Unnamed: 3                                                               17 non-null     str
dtypes: str(18)
memory usage: 6.6 KB

In [44]:
#Bronze municipios
bronze_brasil_municipios = pd.read_csv("Bronze/bronze_municipios.csv", sep=",", encoding="utf-8")
bronze_brasil_municipios.head()

,_aba_origem,ANO DA AVALIAÇÃO,CÓDIGO UF,SIGLA UF,CÓDIGO MUNICÍPIO,NOME DO MUNICÍPIO,REDE,PERCENTUAL DE ALUNOS ALFABETIZADOS - 2023 (1),PERCENTUAL DE ALUNOS ALFABETIZADOS - 2024 (1),META 2024 (2),META 2025,META 2026,META 2027,META 2028,META 2029,META 2030,NIVEL ALFABETIZAÇÃO,PERCENTUAL DE PARTICIPAÇÃO,Unnamed: 1,Unnamed: 2
0,Divulgação Alfabet Municipio,2024,29,BA,2932705,Uruçuca,MUNICIPAL,30,26.42,37.1,44.8,52.75,60.57,67.88,74.41,80,0,82.38341968911918,NaN,NaN
1,Divulgação Alfabet Municipio,2024,42,SC,4209854,Lindóia do Sul,MUNICIPAL,87.4,84.61,80,80,80,80,80,80,80,5,85.18518518518519,NaN,NaN
2,Divulgação Alfabet Municipio,2024,17,TO,1720200,São Miguel do Tocantins,MUNICIPAL,27,36.9,34.18,42.19,50.63,59.04,66.95,74,80,0,88.23529411764706,NaN,NaN
3,Divulgação Alfabet Municipio,2024,31,MG,3105202,Bandeira,MUNICIPAL,62.7,77.5,65.57,68.31,70.92,73.41,75.75,77.95,80,4,100,NaN,NaN
4,Divulgação Alfabet Municipio,2024,43,RS,4307450,Esperança do Sul,MUNICIPAL,97.2,80.10000000000001,80,80,80,80,80,80,80,5,97.22222222222221,NaN,NaN

In [45]:
bronze_brasil_municipios.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   _aba_origem                                     5000 non-null   str
 1   ANO DA AVALIAÇÃO                                4980 non-null   str
 2   CÓDIGO UF                                       4980 non-null   str
 3   SIGLA UF                                        4980 non-null   str
 4   CÓDIGO MUNICÍPIO                                4980 non-null   str
 5   NOME DO MUNICÍPIO                               4980 non-null   str
 6   REDE                                            4980 non-null   str
 7   PERCENTUAL DE ALUNOS ALFABETIZADOS  - 2023 (1)  4868 non-null   str
 8   PERCENTUAL DE ALUNOS ALFABETIZADOS  - 2024 (1)  4980 non-null   str
 9   META 2024 (2)                                   4868 non-null   str
 10  META 2025                                       4980 non-null   str
 11  META 2026                                       4980 non-null   str
 12  META 2027                                       4980 non-null   str
 13  META 2028                                       4980 non-null   str
 14  META 2029                                       4980 non-null   str
 15  META 2030                                       4980 non-null   str
 16  NIVEL ALFABETIZAÇÃO                             4980 non-null   str
 17  PERCENTUAL DE PARTICIPAÇÃO                      4980 non-null   str
 18  Unnamed: 1                                      20 non-null     str
 19  Unnamed: 2                                      20 non-null     str
dtypes: str(20)
memory usage: 781.4 KB

## Dados Camada Silver

In [46]:
#Conhecendo os dados da camada silver (_relatorio_qualidade, silver_alunos, silver_municipios, silver_ufs)

silver_relatorio_qualidade = pd.read_csv("Silver/_relatorio_qualidade.csv", sep=",", encoding="utf-8")
silver_relatorio_qualidade.head(10)

   tabela                 teste            coluna  resultado status
0  alunos  duplicatas_removidas               NaN          0     OK
1  alunos         valores_nulos     ano_avaliacao          0   INFO
2  alunos         valores_nulos         codigo_uf          0   INFO
3  alunos         valores_nulos          sigla_uf          0   INFO
4  alunos         valores_nulos          id_aluno          0   INFO
5  alunos         valores_nulos        tipo_serie          0   INFO
6  alunos         valores_nulos         id_escola          0   INFO
7  alunos         valores_nulos  tipo_dependencia          0   INFO
8  alunos         valores_nulos  codigo_municipio          0   INFO
9  alunos         valores_nulos    nome_municipio          0   INFO

In [47]:
silver_relatorio_qualidade.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tabela     75 non-null     str
 1   teste      75 non-null     str
 2   coluna     72 non-null     str
 3   resultado  75 non-null     int64
 4   status     75 non-null     str
dtypes: int64(1), str(4)
memory usage: 3.1 KB

In [48]:
#silver alunos

silver_alunos = pd.read_csv("Silver/silver_alunos.csv", sep=",", encoding="utf-8")
silver_alunos.head()

,ano_avaliacao,codigo_uf,sigla_uf,id_aluno,tipo_serie,id_escola,tipo_dependencia,codigo_municipio,nome_municipio,presenca_lp,preenchimento_lp,codigo_caderno_lp,peso_aluno_lp,proficiencia_lp,alfabetizado
0,2024,31,MG,31136862,2,60021275,3,3119955,Córrego Fundo,1,1,5,1.07,801.24,1
1,2024,24,RN,24004269,2,60010114,3,2408102,Natal,1,1,18,1.27,751.47,1
2,2024,25,PB,25017200,2,60010962,3,2515302,Sapé,1,1,2,1.10,674.74,0
3,2024,42,SC,42051866,2,60034809,3,4209102,Joinville,1,1,14,1.50,773.11,1
4,2024,23,CE,23038517,2,60009206,3,2304400,Fortaleza,1,1,16,1.00,769.80,1

In [49]:
silver_alunos.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ano_avaliacao      5000 non-null   int64
 1   codigo_uf          5000 non-null   int64
 2   sigla_uf           5000 non-null   str
 3   id_aluno           5000 non-null   int64
 4   tipo_serie         5000 non-null   int64
 5   id_escola          5000 non-null   int64
 6   tipo_dependencia   5000 non-null   int64
 7   codigo_municipio   5000 non-null   int64
 8   nome_municipio     5000 non-null   str
 9   presenca_lp        5000 non-null   int64
 10  preenchimento_lp   5000 non-null   int64
 11  codigo_caderno_lp  5000 non-null   int64
 12  peso_aluno_lp      4371 non-null   float64
 13  proficiencia_lp    4371 non-null   float64
 14  alfabetizado       5000 non-null   int64
dtypes: float64(2), int64(11), str(2)
memory usage: 586.1 KB

In [50]:
#silver municipios

silver_municipios = pd.read_csv("Silver/silver_municipios.csv", sep=",", encoding="utf-8")
silver_municipios.head()

,aba_origem,ano_avaliacao,codigo_uf,sigla_uf,codigo_municipio,nome_municipio,rede,pct_alfabetizados_2023,pct_alfabetizados_2024,meta_2024,meta_2025,meta_2026,meta_2027,meta_2028,meta_2029,meta_2030,nivel_alfabetizacao,pct_participacao
0,Divulgação Alfabet Municipio,2024.0,29.0,BA,2932705.0,Uruçuca,MUNICIPAL,30.0,26.42,37.10,44.80,52.75,60.57,67.88,74.41,80.0,0,82.383420
1,Divulgação Alfabet Municipio,2024.0,42.0,SC,4209854.0,Lindóia do Sul,MUNICIPAL,87.4,84.61,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5,85.185185
2,Divulgação Alfabet Municipio,2024.0,17.0,TO,1720200.0,São Miguel do Tocantins,MUNICIPAL,27.0,36.90,34.18,42.19,50.63,59.04,66.95,74.00,80.0,0,88.235294
3,Divulgação Alfabet Municipio,2024.0,31.0,MG,3105202.0,Bandeira,MUNICIPAL,62.7,77.50,65.57,68.31,70.92,73.41,75.75,77.95,80.0,4,100.000000
4,Divulgação Alfabet Municipio,2024.0,43.0,RS,4307450.0,Esperança do Sul,MUNICIPAL,97.2,80.10,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5,97.222222

In [51]:
silver_municipios.info()

<class 'pandas.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   aba_origem              4981 non-null   str
 1   ano_avaliacao           4979 non-null   float64
 2   codigo_uf               4980 non-null   float64
 3   sigla_uf                4980 non-null   str
 4   codigo_municipio        4980 non-null   float64
 5   nome_municipio          4980 non-null   str
 6   rede                    4980 non-null   str
 7   pct_alfabetizados_2023  4867 non-null   float64
 8   pct_alfabetizados_2024  4979 non-null   float64
 9   meta_2024               4867 non-null   float64
 10  meta_2025               4979 non-null   float64
 11  meta_2026               4979 non-null   float64
 12  meta_2027               4979 non-null   float64
 13  meta_2028               4979 non-null   float64
 14  meta_2029               4979 non-null   float64
 15  meta_2030               4979 non-null   float64
 16  nivel_alfabetizacao     4980 non-null   str
 17  pct_participacao        4979 non-null   float64
dtypes: float64(13), str(5)
memory usage: 700.6 KB

In [52]:
#silver ufs
silver_ufs = pd.read_csv("Silver/silver_ufs.csv", sep=",", encoding="utf-8")
silver_ufs.head()

,aba_origem,ano_avaliacao,codigo_uf,sigla_uf,nome_uf,rede,pct_alfabetizados_2023,pct_alfabetizados_2024,meta_2024,meta_2025,meta_2026,meta_2027,meta_2028,meta_2029,meta_2030,pct_participacao
0,Divulgação Alfabet UF e Brasil,NaN,0.0,SIGLA_UF,NOME_UF,REDE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Divulgação Alfabet UF e Brasil,2024.0,NaN,NaN,Brasil,PÚBLICA,55.90,59.197271,59.9,63.77,67.47,70.97,74.23,77.24,NaN,87.370000
2,Divulgação Alfabet UF e Brasil,2024.0,12.0,AC,Acre,PÚBLICA,NaN,51.380000,NaN,56.90,62.20,67.30,72.00,76.20,NaN,80.869222
3,Divulgação Alfabet UF e Brasil,2024.0,27.0,AL,Alagoas,PÚBLICA,43.88,48.630000,49.7,55.50,61.10,66.50,71.50,76.00,NaN,93.783968
4,Divulgação Alfabet UF e Brasil,2024.0,13.0,AM,Amazonas,PÚBLICA,52.20,49.170000,56.8,61.30,65.60,69.60,73.40,76.90,NaN,79.494774

In [53]:
silver_ufs.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   aba_origem              30 non-null     str
 1   ano_avaliacao           28 non-null     float64
 2   codigo_uf               28 non-null     float64
 3   sigla_uf                28 non-null     str
 4   nome_uf                 29 non-null     str
 5   rede                    29 non-null     str
 6   pct_alfabetizados_2023  25 non-null     float64
 7   pct_alfabetizados_2024  27 non-null     float64
 8   meta_2024               24 non-null     float64
 9   meta_2025               26 non-null     float64
 10  meta_2026               26 non-null     float64
 11  meta_2027               26 non-null     float64
 12  meta_2028               26 non-null     float64
 13  meta_2029               26 non-null     float64
 14  meta_2030               0 non-null      float64
 15  pct_participacao        27 non-null     float64
dtypes: float64(12), str(4)
memory usage: 3.9 KB

## Dados Camada Gold

In [54]:
## _resumo_gold
data_resumo_gold = pd.read_csv("Gold/_resumo_gold.csv", sep=",", encoding="utf-8")
data_resumo_gold.head()

,metrica,valor
0,municipios_gold,4981
1,alunos_gold,5000
2,corte_proficiencia_alfabetizacao,743
3,observacao_ranking_municipal,O ranking municipal é calculado sobre a amostr...

In [55]:
data_resumo_gold.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   metrica  4 non-null      str
 1   valor    4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [56]:
# gold_amostra_alunos
data_gold_amostra_alunos = pd.read_csv("Gold/gold_amostra_alunos.csv", sep=",", encoding="utf-8")
data_gold_amostra_alunos.head()

,ano_avaliacao,codigo_uf,sigla_uf,codigo_municipio,nome_municipio,id_aluno,id_escola,tipo_serie,tipo_dependencia,presenca_lp,preenchimento_lp,codigo_caderno_lp,peso_aluno_lp,proficiencia_lp,alfabetizado_oficial,alfabetizado_calculado_743,divergencia_indicador_743
0,2024,31,MG,3119955,Córrego Fundo,31136862,60021275,2,3,1,1,5,1.07,801.24,1,1.0,0.0
1,2024,24,RN,2408102,Natal,24004269,60010114,2,3,1,1,18,1.27,751.47,1,1.0,0.0
2,2024,25,PB,2515302,Sapé,25017200,60010962,2,3,1,1,2,1.10,674.74,0,0.0,0.0
3,2024,42,SC,4209102,Joinville,42051866,60034809,2,3,1,1,14,1.50,773.11,1,1.0,0.0
4,2024,23,CE,2304400,Fortaleza,23038517,60009206,2,3,1,1,16,1.00,769.80,1,1.0,0.0

In [57]:
# gold_evolucao_temporal_municipios
data_gold_evolucao_temporal_municipios = pd.read_csv("Gold/gold_evolucao_temporal_municipal.csv", sep=",", encoding="utf-8")
data_gold_evolucao_temporal_municipios.head()

,codigo_uf,sigla_uf,codigo_municipio,nome_municipio,pct_alfabetizados,ano
0,0.0,SG_UF,0.0,NO_MUNICIPIO,NaN,2023
1,0.0,SG_UF,0.0,NO_MUNICIPIO,NaN,2024
2,11.0,RO,1100015.0,Alta Floresta D'Oeste,64.60,2023
3,11.0,RO,1100015.0,Alta Floresta D'Oeste,67.79,2024
4,11.0,RO,1100023.0,Ariquemes,62.30,2023

In [58]:
data_gold_evolucao_temporal_municipios.info()

<class 'pandas.DataFrame'>
RangeIndex: 9962 entries, 0 to 9961
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   codigo_uf          9960 non-null   float64
 1   sigla_uf           9960 non-null   str
 2   codigo_municipio   9960 non-null   float64
 3   nome_municipio     9960 non-null   str
 4   pct_alfabetizados  9846 non-null   float64
 5   ano                9962 non-null   int64
dtypes: float64(3), int64(1), str(2)
memory usage: 467.1 KB

In [59]:
#data gold_indicadores_municipios
data_gold_indicadores_municipios = pd.read_csv("Gold/gold_indicadores_municipios.csv", sep=",", encoding="utf-8")
data_gold_indicadores_municipios.head()

,ano_avaliacao,codigo_uf,sigla_uf,codigo_municipio,nome_municipio,rede,pct_alfabetizados_2023,pct_alfabetizados_2024,variacao_2023_2024_pp,meta_2024,...,meta_2025,meta_2026,meta_2027,meta_2028,meta_2029,meta_2030,nivel_alfabetizacao,pct_participacao,ranking_amostra_brasil_2024,ranking_amostra_uf_2024
0,2024.0,29.0,BA,2932705.0,Uruçuca,MUNICIPAL,30.0,26.42,-3.58,37.10,...,44.80,52.75,60.57,67.88,74.41,80.0,0,82.383420,4844.0,312.0
1,2024.0,42.0,SC,4209854.0,Lindóia do Sul,MUNICIPAL,87.4,84.61,-2.79,80.00,...,80.00,80.00,80.00,80.00,80.00,80.0,5,85.185185,697.0,23.0
2,2024.0,17.0,TO,1720200.0,São Miguel do Tocantins,MUNICIPAL,27.0,36.90,9.90,34.18,...,42.19,50.63,59.04,66.95,74.00,80.0,0,88.235294,4464.0,103.0
3,2024.0,31.0,MG,3105202.0,Bandeira,MUNICIPAL,62.7,77.50,14.80,65.57,...,68.31,70.92,73.41,75.75,77.95,80.0,4,100.000000,1251.0,340.0
4,2024.0,43.0,RS,4307450.0,Esperança do Sul,MUNICIPAL,97.2,80.10,-17.10,80.00,...,80.00,80.00,80.00,80.00,80.00,80.0,5,97.222222,1026.0,22.0

In [60]:
data_gold_indicadores_municipios.info()

<class 'pandas.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ano_avaliacao                4979 non-null   float64
 1   codigo_uf                    4980 non-null   float64
 2   sigla_uf                     4980 non-null   str
 3   codigo_municipio             4980 non-null   float64
 4   nome_municipio               4980 non-null   str
 5   rede                         4980 non-null   str
 6   pct_alfabetizados_2023       4867 non-null   float64
 7   pct_alfabetizados_2024       4979 non-null   float64
 8   variacao_2023_2024_pp        4867 non-null   float64
 9   meta_2024                    4867 non-null   float64
 10  gap_meta_2024_pp             4867 non-null   float64
 11  atingiu_meta_2024            4867 non-null   float64
 12  meta_2025                    4979 non-null   float64
 13  meta_2026                    4979 non-null   float64
 14  meta_2027                    4979 non-null   float64
 15  meta_2028                    4979 non-null   float64
 16  meta_2029                    4979 non-null   float64
 17  meta_2030                    4979 non-null   float64
 18  nivel_alfabetizacao          4980 non-null   str
 19  pct_participacao             4979 non-null   float64
 20  ranking_amostra_brasil_2024  4979 non-null   float64
 21  ranking_amostra_uf_2024      4979 non-null   float64
dtypes: float64(18), str(4)
memory usage: 856.2 KB

In [61]:
# gold_indicadores_ufs
data_gold_indicadores_ufs = pd.read_csv("Gold/gold_indicadores_ufs.csv", sep=",", encoding="utf-8")
data_gold_indicadores_ufs.head()

,ano_avaliacao,codigo_uf,sigla_uf,nome_uf,rede,pct_alfabetizados_2023,pct_alfabetizados_2024,variacao_2023_2024_pp,meta_2024,gap_meta_2024_pp,atingiu_meta_2024,meta_2025,meta_2026,meta_2027,meta_2028,meta_2029,meta_2030,pct_participacao,ranking_ufs_2024
0,NaN,0.0,SIGLA_UF,NOME_UF,REDE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024.0,NaN,NaN,Brasil,PÚBLICA,55.90,59.197271,3.297271,59.9,-0.702729,0.0,63.77,67.47,70.97,74.23,77.24,NaN,87.370000,NaN
2,2024.0,12.0,AC,Acre,PÚBLICA,NaN,51.380000,NaN,NaN,NaN,NaN,56.90,62.20,67.30,72.00,76.20,NaN,80.869222,17.0
3,2024.0,27.0,AL,Alagoas,PÚBLICA,43.88,48.630000,4.750000,49.7,-1.070000,0.0,55.50,61.10,66.50,71.50,76.00,NaN,93.783968,20.0
4,2024.0,13.0,AM,Amazonas,PÚBLICA,52.20,49.170000,-3.030000,56.8,-7.630000,0.0,61.30,65.60,69.60,73.40,76.90,NaN,79.494774,19.0

In [62]:
data_gold_indicadores_ufs.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ano_avaliacao           28 non-null     float64
 1   codigo_uf               28 non-null     float64
 2   sigla_uf                28 non-null     str
 3   nome_uf                 29 non-null     str
 4   rede                    29 non-null     str
 5   pct_alfabetizados_2023  25 non-null     float64
 6   pct_alfabetizados_2024  27 non-null     float64
 7   variacao_2023_2024_pp   25 non-null     float64
 8   meta_2024               24 non-null     float64
 9   gap_meta_2024_pp        24 non-null     float64
 10  atingiu_meta_2024       24 non-null     float64
 11  meta_2025               26 non-null     float64
 12  meta_2026               26 non-null     float64
 13  meta_2027               26 non-null     float64
 14  meta_2028               26 non-null     float64
 15  meta_2029               26 non-null     float64
 16  meta_2030               0 non-null      float64
 17  pct_participacao        27 non-null     float64
 18  ranking_ufs_2024        26 non-null     float64
dtypes: float64(16), str(3)
memory usage: 4.6 KB

In [63]:
# gold_resumo_municipal_por_uf
data_gold_resumo_municipal_por_uf = pd.read_csv("Gold/gold_resumo_municipal_por_uf.csv", sep=",", encoding="utf-8")
data_gold_resumo_municipal_por_uf.head()

,sigla_uf,municipios_na_amostra,media_pct_alfabetizados_2023,media_pct_alfabetizados_2024,media_variacao_2023_2024_pp,media_gap_meta_2024_pp,pct_municipios_atingiram_meta_2024,media_participacao
0,AC,21,NaN,43.547143,NaN,NaN,NaN,81.824368
1,AL,92,45.865217,52.868804,7.003587,2.218913,55.434783,95.123037
2,AM,53,48.095652,44.939434,-1.982174,-6.827391,26.086957,85.676982
3,AP,16,42.418750,49.449375,7.030625,1.415625,43.750000,90.072598
4,BA,372,37.565217,36.634946,-0.951712,-7.052853,19.021739,91.941589

In [64]:
data_gold_resumo_municipal_por_uf.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 8 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   sigla_uf                            26 non-null     str
 1   municipios_na_amostra               27 non-null     int64
 2   media_pct_alfabetizados_2023        24 non-null     float64
 3   media_pct_alfabetizados_2024        25 non-null     float64
 4   media_variacao_2023_2024_pp         24 non-null     float64
 5   media_gap_meta_2024_pp              24 non-null     float64
 6   pct_municipios_atingiram_meta_2024  24 non-null     float64
 7   media_participacao                  25 non-null     float64
dtypes: float64(6), int64(1), str(1)
memory usage: 1.8 KB